sudo: false
language: php
php:
  - 5.6
  - 7
  - 7.1
  - 7.2

install:
  - composer install --prefer-dist

script:
  - mkdir -p build/logs
  - composer cs
  - composer test

after_success:
  - travis_retry php vendor/bin/coveralls
