sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7

install:
  - composer install

script:
  - mkdir -p build/logs
  - composer cs
  - composer test

after_success:
  - travis_retry php vendor/bin/coveralls
